import React from 'react';

interface DoodleIconProps {
  name: string;
  className?: string;
}

export const DoodleIcon: React.FC<DoodleIconProps> = ({ name, className = "h-6 w-6" }) => {
  return (
    <img 
      src={`/doodle icons/SVG/${name}`} 
      alt="" 
      className={className}
      style={{ display: 'inline-block' }}
    />
  );
};

// Icon mapping from lucide names to doodle icon paths
export const iconMap: Record<string, string> = {
  // Common icons
  'Users': 'interface/user.svg',
  'User': 'interface/user.svg',
  'Mail': 'interface/mail.svg',
  'Phone': 'interface/phone.svg',
  'MapPin': 'interface/location-pin.svg',
  'Clock': 'interface/clock.svg',
  'Calendar': 'interface/calendar.svg',
  'Heart': 'interface/heart.svg',
  'Zap': 'interface/zap.svg',
  'Target': 'interface/target.svg',
  'Award': 'interface/trophy.svg',
  'Shield': 'interface/shield.svg',
  'Globe': 'interface/globe.svg',
  'Star': 'interface/star.svg',
  'Briefcase': 'interface/suitcase.svg',
  'GraduationCap': 'interface/note.svg',
  'TrendingUp': 'finance/trend-up.svg',
  'TrendingDown': 'finance/trend-down.svg',
  'BarChart3': 'interface/analytics.svg',
  'ChevronDown': 'interface/arrow-down.svg',
  'ChevronUp': 'interface/arrow-up.svg',
  'ArrowRight': 'arrows/arrow-right.svg',
  'ArrowLeft': 'arrows/arrow-left.svg',
  'ArrowUp': 'interface/arrow-up.svg',
  'ArrowDown': 'interface/arrow-down.svg',
  'Play': 'interface/play.svg',
  'Linkedin': 'logos/linkedin.svg',
  'Instagram': 'logos/instagram.svg',
  'MessageCircle': 'interface/message.svg',
  'ThumbsUp': 'hand gestures/thumbs-up.svg',
  'ThumbsDown': 'hand gestures/thumbs-down.svg',
  'Sparkles': 'interface/magic-wand.svg',
  'Building2': 'interface/home.svg',
  'BookOpen': 'interface/doc.svg',
  'Quote': 'interface/message-2.svg',
  'Share2': 'interface/send.svg',
  'Coffee': 'food/drink.svg',
  'Laptop': 'interface/tablet.svg',
  'Lightbulb': 'interface/bulb.svg',
  'CheckCircle': 'interface/tick.svg',
  'AlertCircle': 'interface/caution.svg',
  'Info': 'interface/Info.svg',
  'Search': 'interface/search.svg',
  'Settings': 'interface/setting.svg',
  'Bell': 'interface/bell.svg',
  'Download': 'interface/download.svg',
  'Upload': 'interface/upload.svg',
  'Send': 'interface/send.svg',
  'Trash': 'interface/delete.svg',
  'Edit': 'interface/pencil.svg',
  'Copy': 'interface/copy.svg',
  'Check': 'interface/tick.svg',
  'X': 'interface/cross.svg',
  'Plus': 'interface/doc-add.svg',
  'Minus': 'interface/doc-remove.svg',
  'Menu': 'interface/menu.svg',
  'Home': 'interface/home.svg',
  'Folder': 'interface/folder.svg',
  'File': 'interface/doc.svg',
  'Image': 'interface/photo.svg',
  'Video': 'interface/video-camera.svg',
  'Music': 'interface/music.svg',
  'Lock': 'interface/lock.svg',
  'Eye': 'interface/unhide.svg',
  'EyeOff': 'interface/hide.svg',
  'Link': 'interface/link.svg',
  'Bookmark': 'interface/bookmark.svg',
  'Flag': 'interface/flag.svg',
  'Gift': 'interface/gift.svg',
  'Camera': 'interface/camera.svg',
  'Mic': 'interface/mic.svg',
  'Speaker': 'interface/speaker.svg',
  'Headphones': 'interface/headphone.svg',
  'Wifi': 'interface/signal.svg',
  'Bluetooth': 'interface/bluetooth.svg',
  'Refresh': 'interface/sync.svg',
  'RotateCw': 'interface/sync.svg',
  'Maximize': 'interface/maximize.svg',
  'Minimize': 'interface/minimize.svg',
  'Filter': 'interface/filter.svg',
  'Grid': 'interface/grid.svg',
  'List': 'interface/list.svg',
  'Layers': 'interface/layer.svg',
  'Package': 'interface/gift.svg',
  'ShoppingCart': 'e-commerce/shopping-cart.svg',
  'CreditCard': 'finance/credit-card.svg',
  'DollarSign': 'currency/dollar.svg',
  'PieChart': 'interface/pie.svg',
  'Activity': 'interface/analytics.svg',
  'Server': 'interface/server.svg',
  'Database': 'interface/server.svg',
  'Cloud': 'interface/cloud.svg',
  'CloudUpload': 'interface/cloud-up.svg',
  'CloudDownload': 'interface/cloud-down.svg',
  'Cpu': 'misc/chip.svg',
  'Smartphone': 'interface/phone.svg',
  'Tablet': 'interface/tablet.svg',
  'Watch': 'interface/clock.svg',
  'Rocket': 'misc/rocket.svg',
  'Plane': 'misc/plane.svg',
  'Car': 'misc/car.svg',
  'Truck': 'misc/bus.svg',
  'Ship': 'misc/ship.svg',
  'Navigation': 'interface/navigation.svg',
  'Compass': 'interface/navigation.svg',
  'Map': 'interface/map.svg',
  'Thermometer': 'health/thermometer.svg',
  'Sun': 'interface/sun.svg',
  'Moon': 'weather/moon.svg',
  'CloudRain': 'weather/rain.svg',
  'CloudSnow': 'weather/snow.svg',
  'Wind': 'weather/wind.svg',
  'Flame': 'misc/fire.svg',
  'Bot': 'misc/bot.svg',
  'Bug': 'misc/bug.svg',
  'Code': 'interface/pencil.svg',
  'Terminal': 'interface/tablet.svg',
  'AtSign': 'interface/at-the-rate.svg',
  'Paperclip': 'interface/paper-clip.svg',
  'Scissors': 'interface/cut.svg',
  'Clipboard': 'interface/copy.svg',
  'ClipboardCheck': 'interface/checklist.svg',
  'FileText': 'interface/doc.svg',
  'FilePlus': 'interface/doc-add.svg',
  'FolderPlus': 'interface/folder-add.svg',
  'Archive': 'interface/folder.svg',
  'Inbox': 'interface/mail.svg',
  'MailOpen': 'interface/mail-open.svg',
  'MessageSquare': 'interface/message.svg',
  'PhoneCall': 'interface/call.svg',
  'UserPlus': 'interface/user-add.svg',
  'UserMinus': 'interface/user-remove.svg',
  'UserX': 'interface/user-delete.svg',
  'UserCircle': 'interface/user.svg',
  'LogIn': 'interface/login.svg',
  'LogOut': 'interface/logout.svg',
  'Key': 'interface/key.svg',
  'ShieldCheck': 'interface/shield.svg',
  'AlertTriangle': 'interface/caution.svg',
  'HelpCircle': 'interface/question.svg',
  'Circle': 'interface/record.svg',
  'Square': 'interface/square.svg',
  'Diamond': 'interface/diamond.svg',
  'Palette': 'interface/paint-bucket.svg',
  'Paintbrush': 'interface/pen.svg',
  'PenTool': 'interface/pen-tool.svg',
  'Eraser': 'interface/eraser.svg',
  'Ruler': 'interface/ruler.svg',
  'Crop': 'interface/crop.svg',
  'Move': 'interface/move.svg',
  'ZoomIn': 'interface/zoom-in.svg',
  'ZoomOut': 'interface/zoom-out.svg',
  'Scan': 'interface/scan.svg',
  'Sliders': 'interface/setting.svg',
  'ToggleLeft': 'interface/switch.svg',
  'MoreHorizontal': 'interface/menu.svg',
  'MoreVertical': 'interface/menu-2.svg',
  'SkipBack': 'interface/backward.svg',
  'SkipForward': 'interface/forward.svg',
  'FastForward': 'interface/fast-forward.svg',
  'Rewind': 'interface/fast-rewind.svg',
  'Pause': 'interface/pause.svg',
  'Repeat': 'interface/sync.svg',
  'Shuffle': 'interface/shuffle.svg',
  'Disc': 'interface/record.svg',
  'Radio': 'interface/signal.svg',
  'MicOff': 'interface/mic.svg',
  'Film': 'interface/video-camera.svg',
  'Feather': 'interface/pen.svg',
  'Pen': 'interface/pen.svg',
  'Pencil': 'interface/pencil.svg',
  'AlignLeft': 'interface/left-align.svg',
  'AlignCenter': 'interface/center-align.svg',
  'AlignRight': 'interface/right-align.svg',
  'Columns': 'interface/grid.svg',
  'Rows': 'interface/list.svg',
  'Table': 'interface/grid.svg',
  'Layout': 'interface/grid.svg',
  'LayoutGrid': 'interface/grid-2.svg',
  'LayoutList': 'interface/list.svg',
  'Sidebar': 'interface/drawer.svg',
  'Boxes': 'interface/grid.svg',
  'Box': 'interface/square.svg',
  'Component': 'interface/puzzle.svg',
  'Puzzle': 'interface/puzzle-2.svg',
  'Workflow': 'interface/tree.svg',
  'GitBranch': 'interface/tree-2.svg',
  'Trophy': 'interface/trophy.svg',
  'Medal': 'interface/trophy.svg',
  'Gem': 'interface/diamond.svg',
  'Crown': 'interface/trophy.svg',
  'Wand': 'interface/magic-wand.svg',
  'Smile': 'emojis/happy-emoji.svg',
  'Frown': 'emojis/sad-emoji.svg',
  'Meh': 'emojis/confused-emoji.svg',
  'Laugh': 'emojis/laugh-emoji.svg',
  'RefreshCw': 'interface/sync.svg',
  'HeadphonesIcon': 'interface/headphone.svg',
};

// Helper function to get doodle icon path
export const getDoodleIconPath = (lucideName: string): string => {
  return iconMap[lucideName] || 'interface/question.svg';
};
